### ISSUE TITLE
İssue

### ISSUE THREAD

**Issue by Canbay-Erdogan** [alpersarac/LinkedinJobApplicationAutomationConsole#2]
İ have a issue, when i choose edge browser it is not run. How can i fix it ?

**Comment by alpersarac** [comment]
Sure thing! You can check this page for the implementation of Edge browser.
https://learn.microsoft.com/en-us/microsoft-edge/webdriver-chromium/?tabs=c-sharp

**Comment by Canbay-Erdogan** [comment]
Thanks i will

**Comment by alpersarac** [comment]
My pleasure

**Comment by alpersarac** [comment]
My pleasure
